"""Deterministic derivation of the multi-dump progression fixture set (EUS-07/08).

Companion to ``tests/fixtures/eustack/derive_reference_capture_derivative.py``,
following the same authored-not-observed provenance discipline: this script's
frame chains and thread counts are wholly invented, never copied from the real
out-of-repo eu-stack capture named in ``17-CONTEXT.md`` (a 2.4 MB, multi-file
capture carrying customer host and environment identifiers, which must never
enter this repository). Unlike that script, this one takes no input file at
all -- every byte of every fixture below is generated from the two module-level
tables (``SIGNATURES``, ``DUMPS``) declared here.

Run to regenerate the four committed fixture files::

    uv run python tests/fixtures/eustack/progression/derive_progression_fixtures.py

Thread-identifier reuse across dumps is DELIBERATE, not a bug: this script
resets its TID counter to the same starting value for every dump, and because
each dump's per-signature thread counts differ, the same TID ends up labelling
threads of DIFFERENT signatures in different dumps. That mirrors the real
reference capture's own measured behaviour (roughly 9 threads exited and 10
new ones appeared in 60 seconds on an otherwise idle server) -- the concrete,
measured reason D-10 forbids any per-thread continuity claim in the
progression output. A future reader who "fixes" this reuse by making TIDs
globally unique would silently delete the property the D-10 test fixture
exists to exercise.
"""

from __future__ import annotations

from pathlib import Path

_FIXTURE_DIR = Path(__file__).parent

_PROCESS_NAME = "synthetic-server"
_PID_LINE = f"PID 999001 - {_PROCESS_NAME}\n"
_TID_START = 100_001

_PREAMBLE = (
    "-- deliberately authored eu-stack fixture -- this is NOT a raw capture --\n"
    "-- frame chains are invented, chosen only to classify via the shipped\n"
    "-- src/sift/rules/eustack_roles.toml rules; no relation to any real host --\n"
    "-- thread identifiers are DELIBERATELY reused across this dump SET for\n"
    "-- threads carrying DIFFERENT signatures -- see this file's own module\n"
    "-- docstring for why that is intentional, not a fixture bug --\n"
    "-- generated by: "
    "tests/fixtures/eustack/progression/derive_progression_fixtures.py --\n"
)

# Five authored frame chains, verified against src/sift/rules/eustack_roles.toml
# (each entry a tuple of already-normalise()d frame BODIES, leaf frame first --
# the same order iter_frames() yields them, deepest call first):
#
# - "warehouse": blocked-on-external / warehouse, via rule 16
#   (CDSSQueryEngine::WaitUntilFinished, a `contains` match).
# - "parked": idle-parked / job-queue, via rule 7
#   (MSIQTask::GetNextPreferredJob).
# - "stable": running / compute, via rule 1 (_shi_allocBlock) -- rules 1-5 are
#   tried before any idle/external rule, so this frame chain always resolves
#   to running regardless of what else it contains.
# - "newcomer": blocked-on-external / http, via rule 17 (curl_multi_poll).
# - "departing": idle-parked / command-queue, via rule 9
#   (MSICommandQTask::GetNextCommand) -- a DIFFERENT parking chain from
#   "parked"'s (job-queue, rule 7), so the two collapse to two distinct
#   signatures rather than one.
SIGNATURES: dict[str, tuple[str, ...]] = {
    "warehouse": (
        "pthread_cond_wait@@GLIBC_2.3.2",
        "CDSSQueryEngine::WaitUntilFinished - libcastor.so query_engine.cpp:512",
        "CDSSQueryEngine::Execute",
        "MSIThread::Run",
        "start_thread",
    ),
    "parked": (
        "pthread_cond_wait@@GLIBC_2.3.2",
        "MSIQTask::GetNextPreferredJob - libcastor.so queue_task.cpp:88",
        "MSIQTask::Run",
        "MSIThread::Run",
        "start_thread",
    ),
    "stable": (
        "_shi_allocBlock - libhandler.so alloc.cpp:44",
        "MSIEvaluationTask::Execute",
        "MSIThread::Run",
        "start_thread",
    ),
    "newcomer": (
        "poll",
        "curl_multi_poll - libcurl.so multi.c:1200",
        "CDSSHttpClient::Wait",
        "MSIThread::Run",
        "start_thread",
    ),
    "departing": (
        "pthread_cond_wait@@GLIBC_2.3.2",
        "MSICommandQTask::GetNextCommand - libcastor.so command_task.cpp:77",
        "MSICommandQTask::Run",
        "MSIThread::Run",
        "start_thread",
    ),
}

# (filename, ISO-8601 dump-time timestamp or None, {signature label: thread count}).
#
# Two properties of this table are load-bearing and must not be "tidied up":
#
# 1. The chronological order (charlie 16:07:39, bravo 16:08:37, alpha
#    16:09:35) is the exact REVERSE of sorted filename order (alpha, bravo,
#    charlie) -- the only thing that lets a D-01 test tell timestamp ordering
#    apart from filename ordering.
# 2. "warehouse" runs 3 -> 7 -> 5 across charlie/bravo/alpha: consecutive step
#    deltas +4 and -2, an overall first-to-last delta of +2 -- the
#    grew-then-shrank case D-08 exists to surface, invisible if only the
#    overall figure were reported.
#
# dump_delta_nots.txt carries dump_bravo.txt's identical population with its
# ISO-8601 line omitted entirely (never blanked) -- the D-02 fallback trigger.
# Its filename sorts after dump_charlie.txt, so the untimestamped pair still
# has a well-defined filename ordering to declare.
DUMPS: tuple[tuple[str, str | None, dict[str, int]], ...] = (
    (
        "dump_charlie.txt",
        "2026-04-10T16:07:39+00:00",
        {"warehouse": 3, "parked": 10, "stable": 4, "departing": 2},
    ),
    (
        "dump_bravo.txt",
        "2026-04-10T16:08:37+00:00",
        {"warehouse": 7, "parked": 6, "stable": 4, "newcomer": 2},
    ),
    (
        "dump_alpha.txt",
        "2026-04-10T16:09:35+00:00",
        {"warehouse": 5, "parked": 6, "stable": 4, "newcomer": 2},
    ),
    (
        "dump_delta_nots.txt",
        None,
        {"warehouse": 7, "parked": 6, "stable": 4, "newcomer": 2},
    ),
)


def _thread_block(tid: int, frames: tuple[str, ...]) -> str:
    """One ``TID <n>:`` header plus its ``#<index>  0x<addr>  <symbol>``
    frames, in leaf-first order -- exactly the shape ``_TID_RE``/``_FRAME_RE``
    (``src/sift/adapters/eustack.py``) parse.
    """
    lines = [f"TID {tid}:\n"]
    for index, frame in enumerate(frames):
        addr = 0x700000000000 + tid * 0x100 + index
        lines.append(f"#{index}  0x{addr:016x}  {frame}\n")
    return "".join(lines)


def build_dump_text(ts: str | None, counts: dict[str, int]) -> str:
    """Assemble one dump's full text: preamble, optional dump-time header
    line, PID line, then every signature's threads in ``counts`` order.

    The TID counter always starts at ``_TID_START`` for every dump -- the
    deliberate cross-dump reuse this module's docstring explains.
    """
    parts = [_PREAMBLE]
    if ts is not None:
        parts.append(f"{ts} eu-stack backtrace of process {_PROCESS_NAME}\n")
    parts.append(_PID_LINE)
    tid = _TID_START
    for label, count in counts.items():
        frames = SIGNATURES[label]
        for _ in range(count):
            parts.append(_thread_block(tid, frames))
            tid += 1
    return "".join(parts)


def main() -> None:
    for filename, ts, counts in DUMPS:
        text = build_dump_text(ts, counts)
        (_FIXTURE_DIR / filename).write_text(text, encoding="utf-8")
        print(f"{filename}: {sum(counts.values())} threads")


if __name__ == "__main__":
    main()
